// Here will be types of our actions

export const LOAD = 'LOAD'
export const NOT_LOAD = 'NOT_LOAD'

export const HIDE_MODAL = 'HIDE_MODAL'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SET_MODAL_MESSAGE = 'SET_MODAL_MESSAGE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const GET_DATE_DATA = 'GET_DATE_DATA'
export const CHANGE_MONTH_AMOUNT_FROM_TODAY = 'CHANGE_MONTH_AMOUNT_FROM_TODAY'
export const CHANGE_SELECTED_DATE = 'CHANGE_SELECTED_DATE'
export const CHANGE_CURRENT_YEAR = 'CHANGE_CURRENT_YEAR'
export const CHANGE_SELECTED_YEAR = 'CHANGE_SELECTED_YEAR'

export const GET_CURRENT_USER_ID = 'GET_CURRENT_USER_ID'
