export {default as App} from './App'
export {default as FeaturesPage} from './FeaturesPage/FeaturesPage'
export {default as AddProduct} from './AddProduct'
export {default as ProductSearch} from './ProductSearch'
export {default as CalendarPage} from './CalendarPage'
export {default as Profile} from './Profile'
export {default as Main} from './Main'
export { default as OnboardingPage } from './OnboardingPage/OnboardingPage'
export { default as SignUp } from './SignUp/SignUp'
export { default as OnBoardingSlider } from './OnBoardingSlider/OnBoardingSlider'

